### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by kcubero27** [pepecos/nextjs-preactjs-boilerplate#7]
We need an e2e testing tool. We can either use cypress or playwright. 
Considering that we need to support a huge amount of browsers, we should use playwright.
Debate and choose the best tool.

**Comment by jesugmz** [comment]
Note: consider we want to achieve a mobile-first website.

PD: I'm gonna check both and other options as well to let here more conclusions.

**Comment by kcubero27** [comment]
@tomtobac knows a lot of [cypress](https://www.cypress.io/). We could take advantage of that.
They also provide this list of [browsers](https://docs.cypress.io/es/guides/guides/launching-browsers.html):
- Canary
- Chrome
- Chromium
- Edge
- Edge Beta
- Edge Canary
- Edge Dev
- Electron
- Firefox (Beta support)
- Firefox Developer Edition (Beta support)
- Firefox Nightly (Beta support)

As far as I know, there is an option to fake [viewports](https://docs.cypress.io/api/commands/viewport.html#Syntax) but here is nothing related to Opera or Chrome Android etc.

**Comment by tomtobac** [comment]
Yes, sure, you can test mobile-first views:
- https://docs.cypress.io/api/commands/viewport.html#Syntax
